// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerformanceReviewReminderBot.Web.Data;

#nullable disable

namespace PerformanceReviewReminderBot.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219232633_AddContentMaxLengths")]
    partial class AddContentMaxLengths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("PerformanceReviewReminderBot.Web.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TalentManagerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("TalentManagerId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PerformanceReviewReminderBot.Web.Entities.EmployeeTeammate", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeammateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployeeId", "TeammateId");

                    b.HasIndex("TeammateId");

                    b.ToTable("EmployeeTeammates");
                });

            modelBuilder.Entity("PerformanceReviewReminderBot.Web.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ReviewId", "AuthorId")
                        .IsUnique();

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("PerformanceReviewReminderBot.Web.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.HasIndex("RecipientId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PerformanceReviewReminderBot.Web.Entities.PerformanceReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "ReviewDate");

                    b.ToTable("PerformanceReviews");
                });

            modelBuilder.Entity("PerformanceReviewReminderBot.Web.Entities.Employee", b =>
                {
                    b.HasOne("PerformanceReviewReminderBot.Web.Entities.Employee", "TalentManager")
                        .WithMany("ManagedEmployees")
                        .HasForeignKey("TalentManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TalentManager");
                });

            modelBuilder.Entity("PerformanceReviewReminderBot.Web.Entities.EmployeeTeammate", b =>
                {
                    b.HasOne("PerformanceReviewReminderBot.Web.Entities.Employee", "Employee")
                        .WithMany("EmployeeTeammates")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerformanceReviewReminderBot.Web.Entities.Employee", "Teammate")
                        .WithMany("TeammateOf")
                        .HasForeignKey("TeammateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Teammate");
                });

            modelBuilder.Entity("PerformanceReviewReminderBot.Web.Entities.Feedback", b =>
                {
                    b.HasOne("PerformanceReviewReminderBot.Web.Entities.Employee", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PerformanceReviewReminderBot.Web.Entities.PerformanceReview", "Review")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("PerformanceReviewReminderBot.Web.Entities.Notification", b =>
                {
                    b.HasOne("PerformanceReviewReminderBot.Web.Entities.Employee", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerformanceReviewReminderBot.Web.Entities.PerformanceReview", "Review")
                        .WithMany("Notifications")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Recipient");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("PerformanceReviewReminderBot.Web.Entities.PerformanceReview", b =>
                {
                    b.HasOne("PerformanceReviewReminderBot.Web.Entities.Employee", "Employee")
                        .WithMany("PerformanceReviews")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PerformanceReviewReminderBot.Web.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeTeammates");

                    b.Navigation("ManagedEmployees");

                    b.Navigation("Notifications");

                    b.Navigation("PerformanceReviews");

                    b.Navigation("TeammateOf");
                });

            modelBuilder.Entity("PerformanceReviewReminderBot.Web.Entities.PerformanceReview", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
