// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerformanceReviewBot.Data;

#nullable disable

namespace PerformanceReviewBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PerformanceReviewBot.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsManager")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PerformanceReviewBot.Data.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsManagerFeedback")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerformanceReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("PerformanceReviewId", "ReviewerId")
                        .IsUnique();

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("PerformanceReviewBot.Data.Entities.PerformanceReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "ReviewDate");

                    b.ToTable("PerformanceReviews");
                });

            modelBuilder.Entity("PerformanceReviewBot.Data.Entities.ReminderLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PerformanceReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReminderType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PerformanceReviewId");

                    b.HasIndex("SentDate");

                    b.ToTable("ReminderLogs");
                });

            modelBuilder.Entity("PerformanceReviewBot.Data.Entities.Employee", b =>
                {
                    b.HasOne("PerformanceReviewBot.Data.Entities.Employee", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("PerformanceReviewBot.Data.Entities.Feedback", b =>
                {
                    b.HasOne("PerformanceReviewBot.Data.Entities.PerformanceReview", "PerformanceReview")
                        .WithMany("Feedbacks")
                        .HasForeignKey("PerformanceReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerformanceReviewBot.Data.Entities.Employee", "Reviewer")
                        .WithMany("FeedbacksGiven")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerformanceReview");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("PerformanceReviewBot.Data.Entities.PerformanceReview", b =>
                {
                    b.HasOne("PerformanceReviewBot.Data.Entities.Employee", "Employee")
                        .WithMany("PerformanceReviews")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PerformanceReviewBot.Data.Entities.ReminderLog", b =>
                {
                    b.HasOne("PerformanceReviewBot.Data.Entities.Employee", "Employee")
                        .WithMany("ReminderLogs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PerformanceReviewBot.Data.Entities.PerformanceReview", "PerformanceReview")
                        .WithMany("ReminderLogs")
                        .HasForeignKey("PerformanceReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PerformanceReview");
                });

            modelBuilder.Entity("PerformanceReviewBot.Data.Entities.Employee", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("FeedbacksGiven");

                    b.Navigation("PerformanceReviews");

                    b.Navigation("ReminderLogs");
                });

            modelBuilder.Entity("PerformanceReviewBot.Data.Entities.PerformanceReview", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("ReminderLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
